---
resources:
- name: git
  type: git
  source:
    uri: https://github.com/kethiraj/testpipeline.git
    branch: master
- name: spring-boot-service-docker-repository
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))    

jobs:
  - name: test
    public: true

    plan:
      - get: git
        trigger: true
      - task: mvn-test
        file: "tasks/maven-test.yml"
  - name: package
    public: true
    serial: true
    plan:
      - get: git
        trigger: true
        passed: [test]
      - task: mvn-package
        file: "tasks/maven-package.yml"
      - put: spring-boot-service-docker-repository
        params:
          build: spring-boot-service-out
      
      
  - name: terraform-pipe-line
    plan:
    - get: git
    
    - task: run-terraform
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}
        inputs:
            - name: git        
        run:
            path: sh
            args: 
                - -exc
                - |
                  env
                  ls -lrth
                  cd git
                  ls -ltrh
                  terraform init
        params:
          AWS_ACCESS_KEY_ID: ((access-key))
          AWS_SECRET_ACCESS_KEY: ((secret-key))

    - task: terraform-plan
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}

        inputs:  
          - name: git
        run: 
          path: sh
          args:
                - -exc
                - |
                  env
                  ls -lrth
                  cd git
                  ls -ltrh
                  terraform init
                  terraform plan
        params:
          AWS_ACCESS_KEY_ID: ((access-key))
          AWS_SECRET_ACCESS_KEY: ((secret-key))
    - task: terraform-apply
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}

        inputs:
           - name: git
        run:
          path: sh
          args:
                - -exc
                - |
                  env
                  ls -lrth
                  cd git
                  ls -ltrh
                  terraform init
                  terraform apply -auto-approve
        params:
          AWS_ACCESS_KEY_ID: ((access-key))
          AWS_SECRET_ACCESS_KEY: ((secret-key))
        

    - task: remove-terraform
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}
        inputs:
            - name: git
        run:
            path: sh
            args: 
                - -exc
                - |
                  ls -lrth
                  cd git
                  terraform init
                  terraform destroy --auto-approve        
        params:
          AWS_ACCESS_KEY_ID: ((access-key))
          AWS_SECRET_ACCESS_KEY: ((secret-key))      
