---
resources:
- name: git
  type: git
  source:
    uri: https://github.com/kethiraj/testpipeline.git
    branch: master

- name: terraform-image
  type: git
  source:
    uri: https://github.com/hashicorp/docker-hub-images.git
    branch: master


jobs:
  - name: terraform-pipe-line
    plan:
    - get: git
    - get: terraform-image
    
    - task: run-terraform
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}
        inputs:
            - name: git        
        run:
            path: sh
            args: 
                - -exc
                - |
                  env
                  ls -lrth
                  cd git
                  ls -ltrh
                  terraform init
                  terraform plan
                  terraform apply --auto-approve                             
        params:
          AWS_ACCESS_KEY_ID: ((access-key))
          AWS_SECRET_ACCESS_KEY: ((secret-key))
